### ISSUE TITLE
Documentar el 1er Sprint del SCRUM

### ISSUE THREAD

**Issue by Maveto** [CodeRangersBo/CodeRangersBo#10]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: Tener documentado el avance del 1er sprint
PARA QUE: Tengamos la documentación correcta del proyecto y conocer las tareas ya realizadas

Criterio de Aceptación
Documentar el avance del scrum

**Comment by GeorgeOfSystem** [comment]
**NO olvidar modificar el scrum wiki en caso de existir algún cambio de algún otro punto**

**Comment by GeorgeOfSystem** [comment]
Corregir puntos frágiles que nos mostro @hrnn
