### ISSUE TITLE
Documentar Mockups

### ISSUE THREAD

**Issue by GeorgeOfSystem** [CodeRangersBo/CodeRangersBo#11]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: Tener definido el diseño básico de los Mockups
PARA QUE: Tengamos la documentación correcta del proyecto para su posterior avance

Criterio de Aceptación

- Diagramas básicos de los Mockups
- Dividir entre los usuarios del sistema (administrador, empresa y evaluador )

**Comment by GeorgeOfSystem** [comment]
![archivo](https://user-images.githubusercontent.com/49001431/99769566-e9495100-2adc-11eb-88f0-37ee5d3396a7.png)
![log](https://user-images.githubusercontent.com/49001431/99769571-ea7a7e00-2adc-11eb-8d9b-df4cc1ce9f7f.png)
![New Wireframe 3](https://user-images.githubusercontent.com/49001431/99769572-ea7a7e00-2adc-11eb-8589-827f05ce980c.png)
![New Wireframe 4](https://user-images.githubusercontent.com/49001431/99769573-ea7a7e00-2adc-11eb-9f66-d9d4ebdd417c.png)
![New Wireframe 5](https://user-images.githubusercontent.com/49001431/99769575-eb131480-2adc-11eb-8fa6-f2bd1d029660.png)
![New Wireframe 6](https://user-images.githubusercontent.com/49001431/99769576-eb131480-2adc-11eb-9219-47e92700c27f.png)
![New Wireframe 7](https://user-images.githubusercontent.com/49001431/99769577-ebabab00-2adc-11eb-9ac9-d1af9279d224.png)
![New Wireframe 8](https://user-images.githubusercontent.com/49001431/99769579-ebabab00-2adc-11eb-81ad-94e89c4c3b1c.png)
![New Wireframe 10](https://user-images.githubusercontent.com/49001431/99769581-ebabab00-2adc-11eb-961a-4546442d20a2.png)
![New Wireframe 11](https://user-images.githubusercontent.com/49001431/99769583-ec444180-2adc-11eb-9cd9-b9e1413f47ff.png)
![oratoria](https://user-images.githubusercontent.com/49001431/99769586-ec444180-2adc-11eb-89a0-2e74aa72afaf.png)
![P I Software - Login](https://user-images.githubusercontent.com/49001431/99769589-ec444180-2adc-11eb-8c09-fbcf27b967f4.png)
![P I Software](https://user-images.githubusercontent.com/49001431/99769590-ecdcd800-2adc-11eb-8716-964baa22d313.png)

**Comment by GeorgeOfSystem** [comment]
Punto más débil del proyecto. Favor dividirlos y diseñar los mockups faltantes

**Comment by mauriayllon** [comment]
Verificar, en la wiki que cada mockup tenga su descripción correspondiente
