### ISSUE TITLE
Documentar los casos de uso

### ISSUE THREAD

**Issue by GeorgeOfSystem** [CodeRangersBo/CodeRangersBo#12]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: Tener definido el diseño de los casos de uso
PARA QUE: Tengamos la documentación correcta del proyecto para su posterior avance

Criterio de Aceptación
Diagramas de caso de uso

**Comment by mauriayllon** [comment]
![hisglobal](https://user-images.githubusercontent.com/48989232/99625005-a5374d00-2a05-11eb-91e4-6a027a951a97.png)

**Comment by mauriayllon** [comment]
![aprob4](https://user-images.githubusercontent.com/48989232/99625070-c5ffa280-2a05-11eb-85f1-6e093a115f37.png)

**Comment by mauriayllon** [comment]
![Uploading Untitled Diagram-1.png…]()

**Comment by mauriayllon** [comment]
![Untitled Diagram-1](https://user-images.githubusercontent.com/48989232/99625281-46260800-2a06-11eb-9d1d-d06ef93dacf6.png)

**Comment by mauriayllon** [comment]
![Untitled Diagram-2](https://user-images.githubusercontent.com/48989232/99625400-91d8b180-2a06-11eb-983f-d8e8a4a09743.png)

**Comment by mauriayllon** [comment]
![aprobacion2](https://user-images.githubusercontent.com/48989232/99625460-b2a10700-2a06-11eb-93ba-3f112f3d3dae.png)

**Comment by mauriayllon** [comment]
![prop](https://user-images.githubusercontent.com/48989232/99625657-16c3cb00-2a07-11eb-88b9-02640e56dfb4.png)

**Comment by GeorgeOfSystem** [comment]
Falta diagrama general y corregir errores del docente. EL resto esta muy bien
.

**Comment by mauriayllon** [comment]
Se tiene que verificar en la wiki si cada caso de uso tiene si descripción, y si se cumple con el flujo establecido

**Comment by mauriayllon** [comment]
Modificar el caso de uso de registro y el auditor

**Comment by mauriayllon** [comment]
![aproaudi](https://user-images.githubusercontent.com/48989232/99756678-10dfef80-2ac4-11eb-8b3f-3fb88bec5e24.png)

**Comment by mauriayllon** [comment]
![Diagrama en blanco](https://user-images.githubusercontent.com/48989232/99756691-16d5d080-2ac4-11eb-823a-dbf8f4d8b819.png)

**Comment by mauriayllon** [comment]
![registro](https://user-images.githubusercontent.com/48989232/99756909-a7141580-2ac4-11eb-9667-3cc9080a12e1.png)
