### ISSUE TITLE
Documentar la arquitectura del software

### ISSUE THREAD

**Issue by GeorgeOfSystem** [CodeRangersBo/CodeRangersBo#13]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: Tener definido el diseño de arquitectura
PARA QUE: Tengamos la documentación correcta del proyecto

Criterio de Aceptación
Diagrama general de la arquitectura

**Comment by GeorgeOfSystem** [comment]
Grapicos de la arquitectura del software

![Arquitectura General](https://user-images.githubusercontent.com/49005725/99623110-c0a05900-2a01-11eb-9540-e8dc97edf29d.png)

![Arquitectura Backend (1)](https://user-images.githubusercontent.com/49005725/99868209-d4c98f00-2b96-11eb-96af-dd35f85cc240.png)

![Aquitectura Frontend](https://user-images.githubusercontent.com/49005725/99623113-c138ef80-2a01-11eb-8683-8ed6dcd18fc7.png)

**Comment by mauriayllon** [comment]
Revisar si los gráficos están correctos, si corresponde con los establecidos, y finalmente si dentro de la wiki tienen sus descripciones correspondientes
