### ISSUE TITLE
Crear un proyecto en firebase

### ISSUE THREAD

**Issue by mauriayllon** [CodeRangersBo/CodeRangersBo#16]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: Tener un proyecto en firebase
PARA QUE: se tenga una base de datos a tiempo real

Criterio de Aceptación
Hacer como propietarios a los integrantes de la organización

**Comment by GeorgeOfSystem** [comment]
Proyect creado y a la espera de confirmación para el rol de propietarios a los correos:
- maveto13@gmail.com (@Maveto )
- mauricio.ad1707@gmail.com (@mauriayllon )
- georgeilr99@gmail.com (@GeorgeOfSystem )

**Comment by mauriayllon** [comment]
Se aceptaron las confirmaciones para tener los roles de propietarios, el proyecto de firebase nos ayudará con el manejo de bases de datos y autentificación de usuarios.
