### ISSUE TITLE
Añadir un usuario Admin en la Wiki

### ISSUE THREAD

**Issue by mauriayllon** [CodeRangersBo/CodeRangersBo#18]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: Añadir un usuario admin
PARA QUE: que pueda realizar las operaciones correspondientes

Criterio de Aceptación
no debe existir bienvenida dentro la misma
ni opción a registro

**Comment by GeorgeOfSystem** [comment]
Tarea suspendida para la presentación del siguiente parcial
