### ISSUE TITLE
Subir el proyecto de angular con las dependencias ya instaladas

### ISSUE THREAD

**Issue by GeorgeOfSystem** [CodeRangersBo/CodeRangersBo#19]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: Subir el proyecto de angular a github con las dependencias ya instaladas
PARA QUE:  solucionar los problemas encontrados

Criterio de Aceptación
Verificar carpeta node_modules.Misma sera instalada con el comando nmp i si no la tiene

**Comment by mauriayllon** [comment]
Con el proyecto ya creado, se instalo las dependencias correspondientes para poder trabajar en el proyecto, como ser: bootstrap, angular material, rxjs y demás. Todas las dependencias de encuentran en el archivo package.json
