### ISSUE TITLE
Implementación del Login

### ISSUE THREAD

**Issue by mauriayllon** [CodeRangersBo/CodeRangersBo#20]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: implementar el login
PARA QUE: los usuarios puedan acceder a los servicios con la información de su cuenta

Criterio de Aceptación
Implementarla sobre los servicios de firebase

**Comment by GeorgeOfSystem** [comment]
verificación correcta realizada con el servicio de firebase
