### ISSUE TITLE
Realizar la navegación por modulos para el auditor

### ISSUE THREAD

**Issue by mauriayllon** [CodeRangersBo/CodeRangersBo#22]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: desarrollar la navegación por módulos para el audito
PARA QUE: que el auditor interactúe con la aplicación web

Criterio de Aceptación
tener un routing module

**Comment by GeorgeOfSystem** [comment]
Se realizo exitosamente la navegación dentro los módulos del auditor
