### ISSUE TITLE
Diseñar el home para el auditor

### ISSUE THREAD

**Issue by mauriayllon** [CodeRangersBo/CodeRangersBo#23]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: Diseñar la pantalla home para el auditor 
PARA QUE: que pueda realizar las operaciones correspondientes

Criterio de Aceptación
no debe existir bienvenida dentro la misma

**Comment by GeorgeOfSystem** [comment]
Se realiza el diseño de home, con una pantalla donde se muestra un registro de todos los formularios existentes
