### ISSUE TITLE
DIseño de toda la parte dirigida al auditor 

### ISSUE THREAD

**Issue by mauriayllon** [CodeRangersBo/CodeRangersBo#27]
Historia de Usuario
COMO: Usuario
QUEREMOS: Tener definido los módulos del auditor
PARA QUE: se pueda gozar de los servicios otorgados

Criterio de Aceptación
Se debe diferenciar con la del modulo de empresa

**Comment by GeorgeOfSystem** [comment]
se realizo el diseño de los módulos dirigido al auditor. dentro la mima no se puede registrar de forma independiente un auditor
