### ISSUE TITLE
Rediseño del login y del registro 

### ISSUE THREAD

**Issue by mauriayllon** [CodeRangersBo/CodeRangersBo#28]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: Rediseñar los módulos de login y registro 
PARA QUE: sean más amigable con el usuario final

Criterio de Aceptación
Imprentar HCI y UX.

**Comment by Maveto** [comment]
Se logró realizar completamente el diseño del login, sin embargo, no se llegó a terminar el diseño del registro
