### ISSUE TITLE
Buscar información sobre el swagger para proceder con la implementación

### ISSUE THREAD

**Issue by mauriayllon** [CodeRangersBo/CodeRangersBo#29]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: tener información sobre el swagger
PARA QUE: se proceda a su implementación

Criterio de Aceptación
Implementar el programa de swagger

**Comment by Maveto** [comment]
Se realizó un documento en swagger paramostrar los servicios REST realizados a la base de datos.

![Screenshot 2020-12-04 074639](https://user-images.githubusercontent.com/49005725/101160892-285fc200-3606-11eb-99a6-a963886ea717.png)
![Screenshot 2020-12-04 074856](https://user-images.githubusercontent.com/49005725/101160905-2c8bdf80-3606-11eb-8971-fe91c12f5f89.png)
