### ISSUE TITLE
Asignar Prioridades

### ISSUE THREAD

**Issue by Maveto** [CodeRangersBo/CodeRangersBo#3]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo.
QUEREMOS: asignar las prioridades a las tareas
PARA QUE: podamos completar las tareas más importantes

Criterio de Aceptación
Estimaciones tomadas grupalmente

**Comment by mauriayllon** [comment]
Se debe establecer el orden en el cual realizar las tareas, para que todo coincida y sea organizado.

**Comment by mauriayllon** [comment]
Orden: 
- Descripción
- Requerimientos
- Casos de uso
- Mockups
- Arquitectura

**Comment by mauriayllon** [comment]
Finalizado
