### ISSUE TITLE
Implementación de la base de datos para la empresa

### ISSUE THREAD

**Issue by mauriayllon** [CodeRangersBo/CodeRangersBo#30]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: Implementar la base de datos para la empresa
PARA QUE: la empresa pueda llevar un seguimiento de sus formularios.

Criterio de Aceptación
Crear diferentes servicios en firebase para conectar a la empresa

**Comment by mauriayllon** [comment]
Se crearon los servicios, formularios e historial, los cuales se conectan a la base de datos de firebase

**Comment by GeorgeOfSystem** [comment]
la conexión a la misma se derivo con el uso de una API
