### ISSUE TITLE
Implementación de la base de datos para el auditor

### ISSUE THREAD

**Issue by mauriayllon** [CodeRangersBo/CodeRangersBo#31]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: implementar la base de datos para el auditor
PARA QUE: el auditor obtenga la información del mismo.

Criterio de Aceptación
Utilizar los diferentes servicios creados para conectar con el modulo del auditor y poder utilizarlos

**Comment by GeorgeOfSystem** [comment]
Se cambio la implementación de la base de datos por lo que esta implementación fue destruida.
