### ISSUE TITLE
Documentar la wiki con todos lo requerido para el segundo parcial

### ISSUE THREAD

**Issue by mauriayllon** [CodeRangersBo/CodeRangersBo#32]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: Documentar en la wiki los requerimientos del segundo parcial.
PARA QUE: se realice su revisión correspondiente y se pueda aprender de ello.

Criterio de Aceptación
Documentar:
- diagrama de bases de datos
- diagramas de secuencia y swagger. 
También arreglar casos de uso

**Comment by mauriayllon** [comment]
![WhatsApp Image 2020-12-04 at 01 23 05](https://user-images.githubusercontent.com/48989232/101132128-d191c280-35dc-11eb-8f0c-d5f31eb9db71.jpeg)

**Comment by GeorgeOfSystem** [comment]
se procedió a dividir la tarea para realizar la documentación correspondiente

**Comment by mauriayllon** [comment]
![AprobSec](https://user-images.githubusercontent.com/48989232/101310187-95e93980-3824-11eb-9fe9-83eb3c07d2cd.png)

**Comment by mauriayllon** [comment]
![FormSec](https://user-images.githubusercontent.com/48989232/101310203-a1d4fb80-3824-11eb-86e8-01d71eef9736.png)

**Comment by mauriayllon** [comment]
![logSec](https://user-images.githubusercontent.com/48989232/101311115-16109e80-3827-11eb-8409-845f66026262.png)

**Comment by mauriayllon** [comment]
<img width="498" alt="Screen Shot 2020-12-07 at 01 14 48" src="https://user-images.githubusercontent.com/48989232/101312232-a0f29880-3829-11eb-9a34-32dd554a8339.png">

**Comment by mauriayllon** [comment]
Se terminó la documentación requerida para el segundo parcial.
