### ISSUE TITLE
Hacer Mockups

### ISSUE THREAD

**Issue by mauriayllon** [CodeRangersBo/CodeRangersBo#4]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo.
QUEREMOS: realizar el diseño básico de los Mockups.
PARA QUE: Tengamos la presentación grafica del proyecto.

Criterio de Aceptación

**Comment by hrnn** [comment]
Que partes necesitamos diseñar?

**Comment by GeorgeOfSystem** [comment]
Use Marvel.app to make the Mockups. Or other ?

**Comment by mauriayllon** [comment]
Diseño de registro, que cuente con las casillas de mail, contacto, nombre de la empresa, contraseña y confirmar contraseña

**Comment by mauriayllon** [comment]
Diseño del login, se requerirá:
- Una casilla para el mail o código
- Una casilla para la contraseña

**Comment by mauriayllon** [comment]
Diseño para el home con las pestañas de formularios, historial, etc..

**Comment by mauriayllon** [comment]
Diseño de la pestaña para ingresar y mandar los formulación correspondiente a los planes de seguridad.

**Comment by mauriayllon** [comment]
Diseño de pestaña para el usuario auditor, que pueda ver los planes recibidos para posteriormente poder aceptarlos o rechazarlos, también realizar el del historial del auditor.
