### ISSUE TITLE
Crea tabla "usuarios" en la base de datos en linea de firebase 

### ISSUE THREAD

**Issue by GeorgeOfSystem** [CodeRangersBo/CodeRangersBo#40]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: Creara tabla de usuarios en la base de datos a tiempo real
PARA QUE: Se pueda realizar el C.R.U.D. correspondiente 

Criterio de Aceptación

**Comment by mauriayllon** [comment]
Se añadió una tabla en la base de datos del proyecto en Firebase
