### ISSUE TITLE
Documentar El Home del Proyecto

### ISSUE THREAD

**Issue by GeorgeOfSystem** [CodeRangersBo/CodeRangersBo#9]
Historia de Usuario
COMO: Equipo Dev-CodeRangersBo
QUEREMOS: Tener definido el diseño de arquitectura
PARA QUE: Tengamos la documentación correcta del proyecto para su posterior entrega y presentación del grupo

Criterio de Aceptación
Logo de la UPB para la presentación

**Comment by GeorgeOfSystem** [comment]
Logo UPB
![UPBLogo](https://user-images.githubusercontent.com/49001431/99072377-48addb00-258a-11eb-8413-7ec1b9188d4b.png)

**Comment by mauriayllon** [comment]
Realizar un tipo indice como el que se estableció en moodle de UPB Virtual, revisar que este completo y que todos los puntos coincidan
